version: '3'
services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`zuv.localhost`)'
      - 'traefik.http.routers.frontend.entrypoints=web'
    ports:
      - 8080
    volumes:
      - ./frontend/src:/app/src
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      # - MONGODB_USERNAME=
      # - MONGODB_PASSWORD=
      # - MONGODB_DATABASE=
      - MONGODB_CONNECTION_STRING=mongodb://mongo/zu-verschenken
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=(Host(`zuv.localhost`) && PathPrefix(`/api`))'
      - 'traefik.http.routers.backend.entrypoints=web'
    ports:
      - 3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
  mongo:
    image: mongo
    ports:
      - 27017:27017
