version: '3'
services:
  app:
    image: zu-verschenken
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - MONGODB_USERNAME=
      # - MONGODB_PASSWORD=
      # - MONGODB_DATABASE=
      - MONGODB_CONNECTION_STRING=mongodb://mongo/zu-verschenken
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
      - ./test:/app/test
  mongo:
    image: mongo
    ports:
      - 27017:27017
